#!/bin/bash -x

REPO=${REPO:-rancher}
SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P)"

package() {
  local os arch suffix tag repo env
  os=$1
  arch=$2

  [ "$os"   != "linux" ] && suffix="${suffix}_${os}"
  [ "$arch" != "amd64" ] && suffix="${suffix}_${arch}"

  if $(echo ${tag} | grep -q dirty); then
      tag=dev
  fi
  tag="${VERSION}${suffix}"

  cp bin/$os/$arch/rancher-metadata package-$os-$arch

  [ "$os" == "windows" ] && dhost="$WINDOWS_DOCKER_HOST" || dhost="$DOCKER_HOST"
  DOCKER_HOST=$dhost docker build -t ${REPO}/metadata:${tag} -f package-$os-$arch/Dockerfile package-$os-$arch

  echo ${REPO}/metadata:${tag} >> dist/images
  echo Built ${REPO}/metadata:${tag}
}

source $SCRIPTPATH/version
cd $SCRIPTPATH/..
mkdir -p dist && rm -rf dist/*
for os in $(ls bin); do
  for arch in $(ls bin/$os); do
    package $os $arch
  done
done
